services:
  # TODO: Dockerize app
  #  api-dev:
  #    build:
  #      context: .
  #      target: local
  #    ports:
  #      - "3000:3000"
  mysql:
    image: public.ecr.aws/docker/library/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
    restart: always
    ports:
      - "3311:3306" # Port definition is for local development on the host.
    volumes:
      - ./setup/dbCreation.sql:/docker-entrypoint-initdb.d/A_db_creation.sql
